//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BM_resource.rc
//
#define EXPORT_MODE                     0
#define buttonExStyle                   0
#define staticExStyle                   0
#define radioExStyle                    0
#define pictureExStyle                  0
#define IMPORT_MODE                     1
#define numOverElements                 2
#define current_header_version          2
#define IDR_SPRITE_CONTEXT              4
#define _PHA                            0x48
#define IDD_GENERIC                     101
#define IDI_ICON1                       102
#define IDR_MENU1                       104
#define IDR_MENU2                       105
#define IDR_MAIN_MENU                   105
#define IDD_PORTDUNG                    106
#define IDD_EXPANDROM                   107
#define IDD_DUNGEON                     109
#define IDD_HEADER                      109
#define IDD_DIALOG1                     112
#define IDD_DIALOG2                     113
#define IDD_TESTTOOL                    113
#define IDC_TEXT                        114
#define ID_Menu                         115
#define ID_DATATRANSFER_TEXT            116
#define IDC_IMPORT_TEXT                 117
#define IDC_EXPORT_TEXT                 118
#define IDB_BITMAP1                     121
#define IDB_BITMAP2                     122
#define IDB_BITMAP3                     123
#define IDB_BITMAP4                     124
#define IDB_SPRITE42                    129
#define IDD_OVER_TILES                  133
#define IDR_OVER_SPRITE                 134
#define IDB_STOCK                       137
#define _TXA                            0x8A
#define IDR_BLANK                       138
#define IDR_OVER_STOCK                  139
#define IDB_CUSTOM                      140
#define IDB_DRAWTILE                    141
#define IDB_SELECT                      142
#define IDB_DURP                        143
#define IDB_SPRITE                      144
#define IDB_HOLE                        145
#define IDR_OVER_HOLE                   146
#define IDB_ENTRANCE                    148
#define IDR_OVER_ENTR                   151
#define IDB_EXIT                        152
#define IDR_OVER_EXIT                   153
#define IDB_ITEM                        154
#define IDR_OVER_ITEM                   155
#define IDR_OVER_SELECT                 157
#define IDR_OVER_OBJECT                 158
#define IDR_HOOKS_ASM                   160
#define IDR_GRAPHICS_ASM                161
#define _TAX                            0xAA
#define _PLB                            0xAB
#define IDC_8MB                         1003
#define IDC_12MB                        1004
#define IDC_PORTDUNG                    1004
#define IDC_16MB                        1005
#define IDC_EDITHEADERS                 1005
#define IDC_20MB                        1006
#define IDC_EDITOBJECTS                 1006
#define IDC_24MB                        1007
#define IDC_EDITENTRANCES               1007
#define IDC_28MB                        1008
#define IDC_CHECKHEADERS                1008
#define IDC_32MB                        1009
#define IDC_CHECKENTRANCES              1009
#define IDC_CHECKOBJECTS                1010
#define IDC_ROMSIZE                     1010
#define IDC_CHECKSPRITES                1011
#define IDC_BG0                         1011
#define IDC_EDITSPRITES                 1012
#define IDC_COLLISION                   1012
#define IDC_EFFECT                      1013
#define IDC_DUNGPAL                     1015
#define IDC_DUNGGFX                     1016
#define IDC_DUNGSPR                     1017
#define IDC_ROUTINE1                    1018
#define IDC_ROUTINE2                    1019
#define IDC_DUNGROOM1                   1020
#define IDC_DUNGROOM2                   1021
#define IDC_DUNGROOM3                   1022
#define IDC_DUNGROOM4                   1023
#define IDC_DUNGROOM5                   1024
#define IDC_PLANE1                      1025
#define IDC_PLANE2                      1026
#define IDC_PLANE3                      1027
#define IDC_PLANE4                      1028
#define IDC_PLANE5                      1029
#define IDC_DARKEN                      1030
#define IDC_DROPITEM                    1032
#define IDR_FLOOR1                      1033
#define IDR_FLOOR2                      1034
#define IDE_TYPE                        1035
#define IDE_SUBTYPE                     1036
#define IDC_SPRITENAME                  1041
#define IDC_OVERLORD                    1043
#define IDC_MAPTILES                    1045
#define IDC_STOCK                       1046
#define IDC_CUSTOM                      1047
#define IDC_SELECT                      1048
#define IDC_DRAWTILE                    1049
#define IDC_SPRITE                      1050
#define IDC_ITEM                        1051
#define IDC_ENTRANCE                    1052
#define IDC_EXIT                        1053
#define IDC_HOLE                        1054
#define ID_OW_LABEL1                    1055
#define ID_OW_LABEL2                    1057
#define ID_OW_EDIT1                     1058
#define ID_OW_AREA_EDIT                 1058
#define ID_OW_EDIT2                     1059
#define ID_OW_LABEL3                    1060
#define ID_OW_EDIT3                     1061
#define IDC_TILE_SIZE                   1062
#define ID_EDIT_OVERLAY                 1063
#define ID_OW_EDIT4                     1064
#define IDC_CUSTOM1                     1065
#define IDC_CUSTOM2                     1066
#define ID_AUX_BG_GFX                   1068
#define ID_AUX_SPR_GFX                  1069
#define IDC_PROGRESS1                   1072
#define END_FLAG                        0x1000
#define asm_object_ref_2                0x8746
#define asm_object_ref                  0x874C
#define asm_layout_ref                  0x882D
#define asm_object_ref_4                0x883F
#define asm_object_ref_3                0x8845
#define IDC_LOADROM                     40001
#define IDC_SAVE                        40002
#define IDC_QUIT                        40004
#define IDC_MOVEHEADERS                 40005
#define IDC_MOVEDUNGEONS                40006
#define IDC_MOVEOVERWORLD               40007
#define IDC_OPEN                        40009
#define IDC_DUNGEON                     40013
#define IDC_OVERWORLD                   40014
#define IDC_OVERMAPS                    40015
#define IDC_DUNGMAPS                    40016
#define EX_DUNGEONS                     40018
#define IM_DUNGEONS                     40019
#define IM_OVERWORLD                    40020
#define EX_OVERWORLD                    40021
#define IDC_EXPANDROM                   40023
#define IDC_ROMINFO                     40024
#define ID_ADDSPRITE                    40025
#define ID_DELETESPRITE                 40027
#define ID_ADDSPRITE222_SHIT            40028
#define ID_REMOVE_HOLE                  40028
#define ID_ADDSPRITE222_SHIT2           40029
#define ID_REMOVE_ENTRANCE              40029
#define ID_ADDSPRITE222_SHIT3           40030
#define ID_REMOVE_EXIT                  40030
#define ID_ADDSPRITE222                 40031
#define ID_ADDSPRITE222_SHIT1           40032
#define ID_ADDSPRITE222_SHIT4           40033
#define ID_ADDSPRITE222_SHIT5           40034
#define ID_FUCK3_FUCK3                  40035
#define ID_FUCK2_FUCK2                  40036
#define ID_FUCK_FUCK1                   40037
#define ID_FUCK                         40038
#define ID_FUCK2                        40039
#define ID_FUCK3                        40040
#define ID_FUCK_SAD                     40041
#define ID_FUCK_FUCK3                   40043
#define ID_FUCK_FUCK4                   40044
#define ID_Menu40045                    40045
#define ID_FUCK_DELETESPRITE            40046
#define ID_CLONESPRITE                  40049
#define ID_ADDOVERLORD                  40051
#define ID_DATATRANSFER_SOUND           40052
#define IDC_IMPORT_MUSIC                40057
#define IDC_EXPORT_MUSIC                40059
#define ID_REMOVE_SPRITE                40061
#define ID_OVERSPRITE_ADDSPRITE         40062
#define ID_ADD_SPRITE                   40062
#define IDC_DUMMY                       40063
#define IDC_STOCK_ROCK_SL               40065
#define IDC_STOCK_ROCK_SH               40066
#define IDC_STOCK_BUSH                  40067
#define IDC_STOCK_BUSH2                 40068
#define IDC_STOCK_PEG                   40069
#define IDC_STOCK_ROCK_BL               40070
#define IDC_STOCK_ROCK_BH               40071
#define IDC_STOCK_WARP                  40072
#define IDC_STOCK_ROCKPILE              40073
#define IDC_STOCK_SIGN                  40074
#define IDC_STOCK_GRASS                 40075
#define IDC_STOCK_JUMPPOINT             40076
#define ID_STOCK_ENTRANCE               40077
#define IDC_ADD_HOLE                    40078
#define IDC_DELETE_HOLES                40079
#define IDC_ADD_ENTRANCE                40081
#define IDC_DELETE_ENTRANCES            40082
#define ID_ADD_EXIT                     40083
#define ID_DELETE_EXITS                 40084
#define ID_EXIT_DOWN                    40085
#define ID_EXIT_UP                      40086
#define ID_EXIT_WOODEN                  40087
#define ID_EXIT_BOMBABLE                40088
#define ID_EXIT_SANCTUARY               40089
#define ID_EXIT_PALACE                  40090
#define ID_DELETE_SPRITES_PART          40091
#define ID_ADD_ITEM                     40092
#define ID_REMOVE_ITEM                  40093
#define ID_DELETE_ITEMS                 40094
#define ID_COPY                         40095
#define ID_PASTE                        40096
#define ID_HFLIP                        40097
#define ID_VFLIP                        40098
#define ID_BOTH_FLIP                    40099
#define ID_PAL1                         40100
#define ID_PAL0                         40101
#define ID_PAL2                         40102
#define ID_PAL3                         40103
#define ID_PAL4                         40104
#define ID_PAL5                         40105
#define ID_PAL6                         40106
#define ID_PAL7                         40107
#define ID_LOW_PRIORITY                 40108
#define ID_HIGH_PRIORITY                40109
#define ID_DELETE_SPRITES_AREA          40110
#define ID_GRAPHICS_EXPORT              40111
#define ID_GRAPHICS_IMPORT              40112
#define ID_FALLING_ROCKS                40113
#define ID_OWSPRITECONTEXT              40114
#define asm_header_ref                  0xB5DD
#define asm_header_bank                 0xB5E7
#define asm_num_chests                  0xEBF6
#define asm_chest_ref                   0xEBFB

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         40116
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
